server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://loclahost:3306/spring-cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.valud}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to Simple E-commerce.